server:
  port: 8080
  servlet:
    context-path: /
    
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/mbatis?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mbatis
    password: bitc5600

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
   
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      
file:
  path: C:/Users/it/Documents/GitHub/SpringMyBatisProject/MyBatis/src/main/webapp/userProfile/